version: "3.9"

services:
  app: # Nombre de la aplicaci칩n que ejecutar치 el servicio principal
    build:
      context: .
    ports:
      - "8000:8000"
    volumes: # En donde tendr치n persistencia los datos
      - ./app:/app
    env_file:
      - .env
    command: >
      sh -c "python main.py"
    depends_on:
      - db
    networks:
      - newbridge

  db: # Nombre / Identificador de la base de datos a la que nos conectaremos
    image: mongo:latest
    volumes: # En donde tendr치n persistencia los datos
      - mongo-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - newbridge

networks:
  newbridge:
    driver: bridge

volumes:
  mongo-data:
