version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: >
      sh -c "python main.py"
    depends_on:
      - db
    networks:
      - newbridge

  db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - newbridge

networks:
  newbridge:
    driver: bridge

volumes:
  mongo-data:
